### ISSUE TITLE
RerefiedMultiphaseFoam/ error 

### ISSUE THREAD

**Issue by MadanBK1** [vincentcasseau/hyStrath#156]
I'm trying to install the rarefield multiphase foam solver with openfoam 2.4.0 MNF. When I tried to compile code using the install documentation from source, I received the error(faceNormal), which is shown at the bottom. Can anyone help me?. 

**************************************************************************************************************************************

/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/lagrangian/dsmc/lnInclude/dsmcCloud.H:259:22: warning: \u2018Foam::solidParticleCouplingCloud\u2019 is already a friend of \u2018Foam::dsmcCloud\u2019 [enabled by default]
         friend class solidParticleCouplingCloud;
                      ^
SOURCE=boundaries/derived/solidPatchBoundaries/dsmcSolidDeletionPatch/dsmcSolidDeletionPatch.C ;  g++ -m64 -Dlinux64 -DWM_DP -DUSE_RANDOM -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3 -march=native  -DNoRepository -ftemplate-depth-100 -I/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/finiteVolume/lnInclude -I/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/lagrangian/basic/lnInclude -I/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/meshTools/lnInclude -I/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/lagrangian/molecularDynamics/general/lnInclude -I/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/lagrangian/dsmc/lnInclude -I/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/parallel/decompose/decompositionMethods/lnInclude -IlnInclude -I. -I/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/OpenFOAM/lnInclude -I/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccMNFDPOpt/dsmcSolidDeletionPatch.o
In file included from lnInclude/solidParticleCouplingCloud.H:54:0,
                 from boundaries/derived/solidPatchBoundaries/dsmcSolidDeletionPatch/dsmcSolidDeletionPatch.H:49,
                 from boundaries/derived/solidPatchBoundaries/dsmcSolidDeletionPatch/dsmcSolidDeletionPatch.C:29:
/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/lagrangian/dsmc/lnInclude/dsmcCloud.H:256:22: warning: \u2018Foam::solidParticleCouplingCloud\u2019 is already a friend of \u2018Foam::dsmcCloud\u2019 [enabled by default]
         friend class solidParticleCouplingCloud;
                      ^
/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/lagrangian/dsmc/lnInclude/dsmcCloud.H:257:22: warning: \u2018Foam::solidParticleCouplingCloud\u2019 is already a friend of \u2018Foam::dsmcCloud\u2019 [enabled by default]
         friend class solidParticleCouplingCloud;
                      ^
/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/lagrangian/dsmc/lnInclude/dsmcCloud.H:258:22: warning: \u2018Foam::solidParticleCouplingCloud\u2019 is already a friend of \u2018Foam::dsmcCloud\u2019 [enabled by default]
         friend class solidParticleCouplingCloud;
                      ^
/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/lagrangian/dsmc/lnInclude/dsmcCloud.H:259:22: warning: \u2018Foam::solidParticleCouplingCloud\u2019 is already a friend of \u2018Foam::dsmcCloud\u2019 [enabled by default]
         friend class solidParticleCouplingCloud;
                      ^
SOURCE=boundaries/derived/solidPatchBoundaries/solidSimpleDiffuseWallPatch/solidSimpleDiffuseWallPatch.C ;  g++ -m64 -Dlinux64 -DWM_DP -DUSE_RANDOM -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3 -march=native  -DNoRepository -ftemplate-depth-100 -I/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/finiteVolume/lnInclude -I/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/lagrangian/basic/lnInclude -I/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/meshTools/lnInclude -I/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/lagrangian/molecularDynamics/general/lnInclude -I/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/lagrangian/dsmc/lnInclude -I/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/parallel/decompose/decompositionMethods/lnInclude -IlnInclude -I. -I/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/OpenFOAM/lnInclude -I/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccMNFDPOpt/solidSimpleDiffuseWallPatch.o
In file included from lnInclude/solidParticleCouplingCloud.H:54:0,
                 from boundaries/derived/solidPatchBoundaries/solidSimpleDiffuseWallPatch/solidSimpleDiffuseWallPatch.H:49,
                 from boundaries/derived/solidPatchBoundaries/solidSimpleDiffuseWallPatch/solidSimpleDiffuseWallPatch.C:29:
/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/lagrangian/dsmc/lnInclude/dsmcCloud.H:256:22: warning: \u2018Foam::solidParticleCouplingCloud\u2019 is already a friend of \u2018Foam::dsmcCloud\u2019 [enabled by default]
         friend class solidParticleCouplingCloud;
                      ^
/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/lagrangian/dsmc/lnInclude/dsmcCloud.H:257:22: warning: \u2018Foam::solidParticleCouplingCloud\u2019 is already a friend of \u2018Foam::dsmcCloud\u2019 [enabled by default]
         friend class solidParticleCouplingCloud;
                      ^
/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/lagrangian/dsmc/lnInclude/dsmcCloud.H:258:22: warning: \u2018Foam::solidParticleCouplingCloud\u2019 is already a friend of \u2018Foam::dsmcCloud\u2019 [enabled by default]
         friend class solidParticleCouplingCloud;
                      ^
/mnt/home/k0006390/OpenFOAM/OpenFOAM-2.4.0-MNF/src/lagrangian/dsmc/lnInclude/dsmcCloud.H:259:22: warning: \u2018Foam::solidParticleCouplingCloud\u2019 is already a friend of \u2018Foam::dsmcCloud\u2019 [enabled by default]
         friend class solidParticleCouplingCloud;
                      ^
boundaries/derived/solidPatchBoundaries/solidSimpleDiffuseWallPatch/solidSimpleDiffuseWallPatch.C: In member function \u2018virtual void Foam::solidSimpleDiffuseWallPatch::controlParticle(Foam::solidParticleCoupling&, Foam::solidParticleCoupling::trackingData&)\u2019:
boundaries/derived/solidPatchBoundaries/solidSimpleDiffuseWallPatch/solidSimpleDiffuseWallPatch.C:100:19: error: \u2018class Foam::solidParticleCoupling\u2019 has no member named \u2018faceNormal\u2019
     vector nw = p.faceNormal();
                   ^
make: *** [Make/linux64GccMNFDPOpt/solidSimpleDiffuseWallPatch.o] Error 1

**Comment by stufuug** [comment]
I also have the problem,do you solve it yet ? Thank you

**Comment by MadanBK1** [comment]
I was able to compile the code with Ubuntu 18.04, which includes GCC compiler 7. However, the cluster I was supposed to use had CentOS 7.9. With the same method, I get the same error.

**Comment by stufuug** [comment]
Thank you for your help!I will try it

在 2024-06-03 02:56:48，Madan B K ***@***.***> 写道：

I was able to compile the code with Ubuntu 18.04, which includes GCC compiler 7. However, the cluster I was supposed to use had CentOS 7.9. With the same method, I get the same error.

**Comment by happypeiso** [comment]
I wasn't able to compile the code with Ubuntu 1804 either,and got the same error of faceNormal,is there any good solution?Thank you so much.

**Comment by MadanBK1** [comment]
I was able to compile the code a while ago, but when I try to compile on Ubuntu 18.0, it does not compile. The reason is unknown. I do not want to waste my time with this code because there is no help from the developer. So I'm building my own solver.
